version: 1
owner: matt-riley

# Source of truth for your existing GitHub Star Lists.
# Keep `name` exactly as it appears in: https://github.com/matt-riley?tab=stars
#
# Schema:
# - id: stable slug used in star-list-assignments.yml
# - name: exact list name in GitHub UI
# - description: purpose/scope used for AI classification
lists:
  - id: github-actions
    name: Github Actions
    description: Tools and Actions for use in Github Action workflows
  - id: rust
    name: Rust
    description: Rust lang and ecosystem
  - id: cli-tools
    name: CLI Tools
    description: variety of CLI tools and utilities
  - id: neovim
    name: Neovim
    description: Neovim configuration and plugins
  - id: golang
    name: Golang
    description: Go programming language and ecosystem
  - id: typescript
    name: Typescript
    description: Typescript and ecosystem
  - id: mac-apps
    name: Mac Apps
    description: apps for macOS
  - id: linux-tools
    name: Linux Tools
    description: Linux tools and utilities
  - id: self-hosting
    name: Self-Hosting
    description: Various self-hosted services
  - id: ruby
    name: Ruby
    description: Ruby programming language and ecosystem
  - id: javascript
    name: JavaScript
    description: JavaScript and ecosystem
  - id: gleam
    name: Gleam
    description: Gleam language and ecosystem
  - id: nix
    name: Nix
    description: Nix package manager and NixOS ecosystem
  - id: astro
    name: Astro
    description: Astro framework and ecosystem
  - id: zig
    name: Zig
    description: Zig programming language and ecosystem
  - id: awesome-lists
    name: Awesome Lists
    description: Curated awesome lists and collection repositories
  - id: obsidian
    name: Obsidian
    description: Obsidian plugins, tools, and workflows
  - id: bun
    name: Bun
    description: Bun runtime and ecosystem
  - id: vlang
    name: Vlang
    description: Vlang programming language and ecosystem
  - id: zsh
    name: zsh
    description: zsh shell tooling and configuration
  - id: k8s
    name: k8s
    description: Kubernetes tools and ecosystem
  - id: elixir
    name: Elixir
    description: Elixir language and ecosystem
