version: 1
owner: matt-riley
assignments:
  Adversis/tailsnitch: golang
  ChartGPU/ChartGPU: typescript
  ClavixDev/Clavix: typescript
  Dispatcharr/Dispatcharr: self-hosting
  Lissy93/Brewfile: ruby
  Xithrius/twitch-tui: rust
  aperturerobotics/goscript: typescript
  awesome-opencode/awesome-opencode: javascript
  block/goose: rust
  charmbracelet/fantasy: golang
  danyjacob45/go-concurrency-exercises: golang
  different-ai/openwork: typescript
  enulus/OpenPackage: typescript
  github/copilot-sdk: typescript
  github/gh-aw: golang
  huseyinbabal/taws: rust
  lucasgelfond/zerobrew: rust
  magicalne/nvim.ai: neovim
  maximhq/bifrost: golang
  mucansever/widelogger: golang
  mutablelogic/go-whisper: golang
  olimorris/codecompanion.nvim: neovim
  openclaw/openclaw: typescript
  rapidaai/voice-ai: golang
  tw93/Mole: mac-apps
  yoanbernabeu/grepai: golang
