name: Update Readme
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  do_the_thing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2.3.4
      - name: Update the SVG
        uses: ./.github/actions/update_svg
        with:
          name: "Matt Riley"
          os: "manjaro"
          editor: "nvim"
          home: "leeds"
          languages: "typescript, javascript, ruby"
